export default {
  INVALID_REQUEST: "Error.INVALID_REQUEST",
  INVALID_INPUT_FILE_TYPE: "Error.INVALID_INPUT_FILE_TYPE",
  UNSUPPORTED_INPUT_FILE_TYPE: "Error.UNSUPPORTED_INPUT_FILE_TYPE",
  GENERIC_ERROR: "Error.GENERIC_ERROR",
  AUTHENTICATION_FAILED: "Error.AUTHENTICATION_FAILED",
};